title          : ICESEE on GHUB
author         : Brian KYANJO
copyright      : "2026"
logo           : icesee_logo.png
only_build_toc_files: true

html:
  use_edit_page_button: false
  use_repository_button: true
  use_issues_button: true
  use_download_button: true
  home_page_in_navbar: false

# bibtex_bibfiles:
#  - refs.bib

# bibtex_reference_style: author_year

repository:
  url: https://github.com/ICESEE-project/ICESEE
  branch: master
  
execute:
  execute_notebooks : 'force'
  timeout           : 30
  allow_errors      : false